version: '3.9'

services:
    server:
       environment: 
        - DATABASE_URL=${DATABASE_URL}
        - PORT=${PORT:-8080}
       env_file:
        - ./be/.env
       build:
        context: ..
        dockerfile: apps/be/dockerfile
       container_name: express-be
       ports: 
       - "8080:8080"
       networks:
        - fullstack-net
       restart: unless-stopped
    client:
       environment:
        - NEXT_PUBLIC_API_URL=http://server:8080
        - PORT=${PORT:-3000}
       build:
        context: ..
        dockerfile: apps/web/dockerfile
       container_name: next-fe
       ports: 
       - "3000:3000"
       networks:
        - fullstack-net
       
       depends_on:
        - server
       restart: unless-stopped
    

networks:
  fullstack-net:
    driver: bridge