name : Deploy to prod
on : 
  push:
     branches: [ new_main ]
      
jobs:
  redeploy_everything:
     runs-on: ubuntu-latest
     name: Deploying all
     steps:
      - run: |
          
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/SSH_KEY
          chmod 600 ~/SSH_KEY
          
          
          ssh -i ~/SSH_KEY -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            # ----------------------------------

            cd turbo-repo-staging
            git pull origin new_main
            pnpm install
            pnpm run build
            pm2 restart all
          EOF

